# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ca395f86be3c7e9dd0619bcd5c7405666eafbed47c701878b30952217260b777f677ea96e47029fe3277ab269e97a4b0a936afdb906c0616ce85a2879158da

test:
  secret_key_base: 03bc855f219875c968cdf80f49d000f1bba75c623beee99ae100ff3c6dd1bf738e43a4ffed6d345d6e78ed1719206172d4454b7d1f2d53ff2b7e9e2c0cc4ce2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
